export default [
  {
    title: 'Node.js',
    icon: 'nodejs.svg',
    link: 'https://expressjs.com',
    github: 'https://github.com/aserto-dev/aserto-node',
    docs: '/docs/software-development-kits/javascript/express',
  },
  {
    title: 'React.js',
    icon: 'react.svg',
    link: 'https://reactjs.org',
    github: 'https://github.com/aserto-dev/aserto-react',
    docs: '/docs/software-development-kits/javascript/react',
  },
  {
    title: 'JavaScript SPA',
    icon: 'javascript.svg',
    link: 'https://www.javascript.com',
    github: 'https://github.com/aserto-dev/aserto-spa-js',
    docs: '/docs/software-development-kits/javascript/spa',
  },
  {
    title: 'Go',
    icon: 'go.svg',
    link: 'https://go.dev/',
    github: 'https://github.com/aserto-dev/go-aserto',
    docs: '/docs/software-development-kits/go/install',
  },
  {
    title: 'Python',
    icon: 'python.svg',
    link: 'https://www.python.org',
    github: 'https://github.com/aserto-dev/aserto-python',
    docs: '/docs/software-development-kits/python/api-client',
  },
  {
    title: 'Flask',
    icon: 'flask.svg',
    link: 'https://flask.palletsprojects.com',
    github: 'https://github.com/aserto-dev/flask-aserto',
    docs: '/docs/software-development-kits/python/flask',
  },
  {
    title: 'Java',
    icon: 'java.svg',
    link: 'https://www.java.com/en/',
    github: 'https://github.com/aserto-dev/java-authorizer',
    docs: '/docs/software-development-kits/java/authorizer',
  },
  {
    title: 'Java Spring',
    icon: 'spring.svg',
    link: 'https://www.java.com/en/',
    github: 'https://github.com/aserto-dev/aserto-spring',
    docs: '/docs/software-development-kits/java/middleware',
  },
  {
    title: 'ASP.NET Core',
    icon: 'dotnet-core.svg',
    link: 'https://dotnet.microsoft.com/apps/aspnet',
    github: 'https://github.com/aserto-dev/aserto-dotnet',
    docs: '/docs/software-development-kits/dotnetcore',
  },
  {
    title: 'Ruby',
    icon: 'ruby.svg',
    link: 'https://www.ruby-lang.org/en/',
    github: 'https://github.com/aserto-dev/aserto-ruby',
    docs: '/docs/software-development-kits/ruby/middleware',
  },
  {
    title: 'Ruby on Rails',
    icon: 'rails.svg',
    link: 'https://rubyonrails.org/',
    github: 'https://github.com/aserto-dev/aserto-rails',
    docs: '/docs/software-development-kits/ruby/rails',
  },
]
